<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountriesTable extends Migration {

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {

        //
        Schema::create('countries', function(Blueprint $t)
        {
            $t->engine= 'MyISAM';
            $t->increments('id');
            $t->string('name',40);
            $t->string('code',3);
        });

        DB::statement("
INSERT INTO `countries` (`id`, `name`, `code`)
VALUES
	(5,'Åland Islands','AX'),
	(4,'Afghanistan','AF'),
	(6,'Albania','AL'),
	(7,'Algeria','DZ'),
	(8,'American Samoa','AS'),
	(9,'Andorra','AD'),
	(10,'Angola','AO'),
	(11,'Anguilla','AI'),
	(12,'Antarctica','AQ'),
	(13,'Antigua and Barbuda','AG'),
	(14,'Argentina','AR'),
	(15,'Armenia','AM'),
	(16,'Aruba','AW'),
	(17,'Australia','AU'),
	(18,'Austria','AT'),
	(19,'Azerbaijan','AZ'),
	(20,'Bahamas','BS'),
	(21,'Bahrain','BH'),
	(22,'Bangladesh','BD'),
	(23,'Barbados','BB'),
	(24,'Belarus','BY'),
	(25,'Belgium','BE'),
	(26,'Belize','BZ'),
	(27,'Benin','BJ'),
	(28,'Bermuda','BM'),
	(29,'Bhutan','BT'),
	(30,'Bolivia','BO'),
	(31,'Bonaire','BQ'),
	(32,'Bosnia and Herzegovina','BA'),
	(33,'Botswana','BW'),
	(34,'Bouvet Island','BV'),
	(35,'Brazil','BR'),
	(36,'British Indian Ocean Territory','IO'),
	(37,'Brunei','BN'),
	(38,'Bulgaria','BG'),
	(39,'Burkina Faso','BF'),
	(40,'Burundi','BI'),
	(41,'Cabo Verde','CV'),
	(42,'Cambodia','KH'),
	(43,'Cameroon','CM'),
	(44,'Canada','CA'),
	(45,'Cayman Islands','KY'),
	(46,'Central African Republic','CF'),
	(47,'Chad','TD'),
	(48,'Chile','CL'),
	(49,'China','CN'),
	(50,'Christmas Island','CX'),
	(51,'Cocos (Keeling) Islands','CC'),
	(52,'Colombia','CO'),
	(53,'Comoros','KM'),
	(54,'Congo','CG'),
	(55,'Congo (DRC)','CD'),
	(56,'Cook Islands','CK'),
	(57,'Costa Rica','CR'),
	(58,'Croatia','HR'),
	(59,'Cuba','CU'),
	(60,'Curaçao','CW'),
	(61,'Cyprus','CY'),
	(62,'Czech Republic','CZ'),
	(63,'Denmark','DK'),
	(64,'Djibouti','DJ'),
	(65,'Dominica','DM'),
	(66,'Dominican Republic','DO'),
	(67,'Ecuador','EC'),
	(68,'Egypt','EG'),
	(69,'El Salvador','SV'),
	(70,'Equatorial Guinea','GQ'),
	(71,'Eritrea','ER'),
	(72,'Estonia','EE'),
	(73,'Ethiopia','ET'),
	(74,'Falkland Islands','FK'),
	(75,'Faroe Islands','FO'),
	(76,'Fiji Islands','FJ'),
	(77,'Finland','FI'),
	(78,'France','FR'),
	(79,'French Guiana','GF'),
	(80,'French Polynesia','PF'),
	(81,'French Southern and Antarctic Lands','TF'),
	(82,'Gabon','GA'),
	(83,'Gambia, The','GM'),
	(84,'Georgia','GE'),
	(85,'Germany','DE'),
	(86,'Ghana','GH'),
	(87,'Gibraltar','GI'),
	(88,'Greece','GR'),
	(89,'Greenland','GL'),
	(90,'Grenada','GD'),
	(91,'Guadeloupe','GP'),
	(92,'Guam','GU'),
	(93,'Guatemala','GT'),
	(94,'Guernsey','GG'),
	(95,'Guinea','GN'),
	(96,'Guinea-Bissau','GW'),
	(97,'Guyana','GY'),
	(98,'Haiti','HT'),
	(99,'Heard Island and McDonald Islands','HM'),
	(100,'Holy See (Vatican City)','VA'),
	(101,'Honduras','HN'),
	(102,'Hong Kong SAR','HK'),
	(103,'Hungary','HU'),
	(104,'Iceland','IS'),
	(105,'India','IN'),
	(106,'Indonesia','ID'),
	(107,'Iran','IR'),
	(108,'Iraq','IQ'),
	(109,'Ireland','IE'),
	(110,'Isle of Man','IM'),
	(111,'Israel','IL'),
	(112,'Italy','IT'),
	(113,'Jamaica','JM'),
	(114,'Jan Mayen','SJ'),
	(115,'Japan','JP'),
	(116,'Jersey','JE'),
	(117,'Jordan','JO'),
	(118,'Kazakhstan','KZ'),
	(119,'Kenya','KE'),
	(120,'Kiribati','KI'),
	(121,'Korea','KR'),
	(122,'Kuwait','KW'),
	(123,'Kyrgyzstan','KG'),
	(124,'Laos','LA'),
	(125,'Latvia','LV'),
	(126,'Lebanon','LB'),
	(127,'Lesotho','LS'),
	(128,'Liberia','LR'),
	(129,'Libya','LY'),
	(130,'Liechtenstein','LI'),
	(131,'Lithuania','LT'),
	(132,'Luxembourg','LU'),
	(133,'Macao SAR','MO'),
	(134,'Macedonia, Former Yugoslav Republic of','MK'),
	(135,'Madagascar','MG'),
	(136,'Malawi','MW'),
	(137,'Malaysia','MY'),
	(138,'Maldives','MV'),
	(139,'Mali','ML'),
	(140,'Malta','MT'),
	(141,'Marshall Islands','MH'),
	(142,'Martinique','MQ'),
	(143,'Mauritania','MR'),
	(144,'Mauritius','MU'),
	(145,'Mayotte','YT'),
	(146,'Mexico','MX'),
	(147,'Micronesia','FM'),
	(148,'Moldova','MD'),
	(149,'Monaco','MC'),
	(150,'Mongolia','MN'),
	(151,'Montenegro','ME'),
	(152,'Montserrat','MS'),
	(153,'Morocco','MA'),
	(154,'Mozambique','MZ'),
	(155,'Myanmar','MM'),
	(156,'Namibia','NA'),
	(157,'Nauru','NR'),
	(158,'Nepal','NP'),
	(159,'Netherlands','NL'),
	(160,'New Caledonia','NC'),
	(161,'New Zealand','NZ'),
	(162,'Nicaragua','NI'),
	(163,'Niger','NE'),
	(164,'Nigeria','NG'),
	(165,'Niue','NU'),
	(166,'Norfolk Island','NF'),
	(167,'North Korea','KP'),
	(168,'Northern Mariana Islands','MP'),
	(169,'Norway','NO'),
	(170,'Oman','OM'),
	(171,'Pakistan','PK'),
	(172,'Palau','PW'),
	(173,'Palestinian Authority','PS'),
	(174,'Panama','PA'),
	(175,'Papua New Guinea','PG'),
	(176,'Paraguay','PY'),
	(177,'Peru','PE'),
	(178,'Philippines','PH'),
	(179,'Pitcairn Islands','PN'),
	(180,'Poland','PL'),
	(181,'Portugal','PT'),
	(182,'Puerto Rico','PR'),
	(183,'Qatar','QA'),
	(184,'Republic of Côte d\'Ivoire','CI'),
	(185,'Reunion','RE'),
	(186,'Romania','RO'),
	(187,'Russia','RU'),
	(188,'Rwanda','RW'),
	(189,'Saba','XS'),
	(190,'Saint Helena, Ascension and Tristan da C','SH'),
	(191,'Samoa','WS'),
	(192,'San Marino','SM'),
	(193,'São Tomé and Príncipe','ST'),
	(194,'Saudi Arabia','SA'),
	(195,'Senegal','SN'),
	(196,'Serbia','RS'),
	(197,'Seychelles','SC'),
	(198,'Sierra Leone','SL'),
	(199,'Singapore','SG'),
	(200,'Sint Eustatius','XE'),
	(201,'Sint Maarten','SX'),
	(202,'Slovakia','SK'),
	(203,'Slovenia','SI'),
	(204,'Solomon Islands','SB'),
	(205,'Somalia','SO'),
	(206,'South Africa','ZA'),
	(207,'South Georgia and the South Sandwich Isl','GS'),
	(208,'Spain','ES'),
	(209,'Sri Lanka','LK'),
	(210,'St. Barthélemy','BL'),
	(211,'St. Kitts and Nevis','KN'),
	(212,'St. Lucia','LC'),
	(213,'St. Martin','MF'),
	(214,'St. Pierre and Miquelon','PM'),
	(215,'St. Vincent and the Grenadines','VC'),
	(216,'Sudan','SD'),
	(217,'Suriname','SR'),
	(218,'Swaziland','SZ'),
	(219,'Sweden','SE'),
	(220,'Switzerland','CH'),
	(221,'Syria','SY'),
	(222,'Taiwan','TW'),
	(223,'Tajikistan','TJ'),
	(224,'Tanzania','TZ'),
	(225,'Thailand','TH'),
	(226,'Timor-Leste','TL'),
	(227,'Togo','TG'),
	(228,'Tokelau','TK'),
	(229,'Tonga','TO'),
	(230,'Trinidad and Tobago','TT'),
	(231,'Tunisia','TN'),
	(232,'Turkey','TR'),
	(233,'Turkmenistan','TM'),
	(234,'Turks and Caicos Islands','TC'),
	(235,'Tuvalu','TV'),
	(236,'Uganda','UG'),
	(237,'Ukraine','UA'),
	(238,'United Arab Emirates','AE'),
	(239,'United Kingdom','UK'),
	(240,'United States','US'),
	(241,'United States Minor Outlying Islands','UM'),
	(242,'Uruguay','UY'),
	(243,'Uzbekistan','UZ'),
	(244,'Vanuatu','VU'),
	(245,'Venezuela','VE'),
	(246,'Vietnam','VN'),
	(247,'Virgin Islands, British','VG'),
	(248,'Virgin Islands, U.S.','VI'),
	(249,'Wallis and Futuna','WF'),
	(250,'Yemen','YE'),
	(251,'Zambia','ZM'),
	(252,'Zimbabwe','ZW');
        ");
        /*!40000 ALTER TABLE `countries` ENABLE KEYS

        UNLOCK TABLES;
        ;*/
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }

}

